# Generated by Django 4.2.3 on 2023-07-26 15:11

import django.contrib.postgres.indexes
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGinExtension(),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['full_name'], name='full_name_gin_idx'), django.contrib.postgres.indexes.GinIndex(fields=['short_name'], name='short_name_gin_idx')],
            },
        ),
    ]
