# Generated by Django 4.2.3 on 2023-07-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='search_vector',
            field=models.TextField(blank=True, null=True),
        ),
    ]
